server:
  port: 8281 #端口
spring:
  devtools:
    enabled: true
    http:
      encoding: #请求编码
        charset: UTF-8
        force: true
        enabled: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/views/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

  profiles:
    active: test
  #连接池 HikariCP
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  aop: # 开启切面管理
    auto: true
mybatis:
  mapperLocations: classpath:mapper/*.xml

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    username: tty_test
    password: 12345@com
    url: jdbc:mysql://localhost:3307/platform?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&allowMultiQueries=true

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/
